name: app_store_runtime
description: Store app runtime bootstrap package for Maslaki split architecture.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  core_auth:
    path: ../core_auth
  core_design_system:
    path: ../core_design_system
  core_localization:
    path: ../core_localization
  core_networking:
    path: ../core_networking
  core_notifications:
    path: ../core_notifications
  core_storage:
    path: ../core_storage
  dio: ^5.7.0
  image_picker: ^1.1.2
  image_picker_android: ^0.8.13+14
  image_picker_platform_interface: ^2.11.1
