BEGIN;

ALTER TABLE app_user
ADD COLUMN IF NOT EXISTS social_show_phone BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE app_user
ADD COLUMN IF NOT EXISTS social_posts_public BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE app_user
ADD COLUMN IF NOT EXISTS social_stories_public BOOLEAN NOT NULL DEFAULT TRUE;

COMMIT;
