BEGIN;

ALTER TABLE inventory_audit_log
  ADD COLUMN IF NOT EXISTS actor_role VARCHAR(40),
  ADD COLUMN IF NOT EXISTS variant_id BIGINT,
  ADD COLUMN IF NOT EXISTS reason TEXT,
  ADD COLUMN IF NOT EXISTS unavailable_until TIMESTAMPTZ;

COMMIT;
