// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-H43YYDhymZWezTY9vEMfN2rTKRgLjiw',
    appId: '1:1016190459986:android:9efc0d2446d7b1e1117f8b',
    messagingSenderId: '1016190459986',
    projectId: 'maslaki-61a97',
    storageBucket: 'maslaki-61a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPPW1nK9IJa96x-dkP5g_fdynRWr7zBc',
    appId: '1:1016190459986:ios:c5b50c71d533fe0f117f8b',
    messagingSenderId: '1016190459986',
    projectId: 'maslaki-61a97',
    storageBucket: 'maslaki-61a97.firebasestorage.app',
    iosBundleId: 'com.maslaki.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwUhhCl-MONjtOl8oddvmwvqZUFEvQ5M8',
    appId: '1:1016190459986:web:f8aa889b7a8a354e117f8b',
    messagingSenderId: '1016190459986',
    projectId: 'maslaki-61a97',
    authDomain: 'maslaki-61a97.firebaseapp.com',
    storageBucket: 'maslaki-61a97.firebasestorage.app',
    measurementId: 'G-MYS8SC0PJ5',
  );
}
