name: app_user_runtime
description: User app runtime bootstrap package for Maslaki split architecture.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  core_auth:
    path: ../core_auth
  core_design_system:
    path: ../core_design_system
  core_localization:
    path: ../core_localization
  core_notifications:
    path: ../core_notifications
  core_networking:
    path: ../core_networking
  core_maps:
    path: ../core_maps
  core_storage:
    path: ../core_storage
  file_picker: ^8.1.2
  shared_models:
    path: ../shared_models
  social_core:
    path: ../social_core
  social_ui:
    path: ../social_ui
