export const carCatalog = [
  {
    brand: "Toyota",
    models: [
      "Corolla",
      "Camry",
      "Yaris",
      "Avalon",
      "Crown",
      "Prius",
      "RAV4",
      "C-HR",
      "Land Cruiser",
      "Prado",
      "Hilux",
      "Fortuner",
      "Rush",
    ],
  },
  {
    brand: "Nissan",
    models: [
      "Sunny",
      "Sentra",
      "Altima",
      "Maxima",
      "Patrol",
      "X-Trail",
      "Kicks",
      "Juke",
      "Navara",
      "370Z",
    ],
  },
  {
    brand: "Hyundai",
    models: [
      "Accent",
      "Elantra",
      "Sonata",
      "Azera",
      "i10",
      "i20",
      "Creta",
      "Tucson",
      "Santa Fe",
      "Palisade",
      "Staria",
    ],
  },
  {
    brand: "Kia",
    models: [
      "Picanto",
      "Rio",
      "Cerato",
      "K5",
      "K8",
      "Seltos",
      "Sportage",
      "Sorento",
      "Telluride",
      "Carens",
    ],
  },
  {
    brand: "Chevrolet",
    models: [
      "Spark",
      "Aveo",
      "Malibu",
      "Impala",
      "Captiva",
      "Trailblazer",
      "Traverse",
      "Tahoe",
      "Suburban",
      "Silverado",
    ],
  },
  {
    brand: "Ford",
    models: [
      "Figo",
      "Focus",
      "Fusion",
      "Taurus",
      "Mustang",
      "Explorer",
      "Edge",
      "Expedition",
      "Ranger",
      "F-150",
    ],
  },
  {
    brand: "Honda",
    models: ["City", "Civic", "Accord", "CR-V", "HR-V", "Pilot", "Odyssey", "Jazz"],
  },
  {
    brand: "Mazda",
    models: ["Mazda 2", "Mazda 3", "Mazda 6", "CX-3", "CX-5", "CX-9", "BT-50", "MX-5"],
  },
  {
    brand: "Mitsubishi",
    models: [
      "Lancer",
      "Attrage",
      "ASX",
      "Outlander",
      "Pajero",
      "Montero Sport",
      "Eclipse Cross",
      "L200",
    ],
  },
  {
    brand: "Suzuki",
    models: ["Alto", "Swift", "Ciaz", "Ertiga", "Vitara", "Jimny", "Baleno", "Dzire"],
  },
  {
    brand: "Volkswagen",
    models: ["Polo", "Golf", "Passat", "Jetta", "Tiguan", "Touareg", "T-Roc", "Arteon"],
  },
  {
    brand: "BMW",
    models: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6"],
  },
  {
    brand: "Mercedes-Benz",
    models: ["A-Class", "C-Class", "E-Class", "S-Class", "CLA", "GLA", "GLC", "GLE", "GLS", "G-Class"],
  },
  { brand: "Audi", models: ["A3", "A4", "A6", "A8", "Q2", "Q3", "Q5", "Q7", "Q8"] },
  { brand: "Lexus", models: ["IS", "ES", "LS", "UX", "NX", "RX", "GX", "LX"] },
  { brand: "Renault", models: ["Logan", "Symbol", "Megane", "Duster", "Koleos", "Captur", "Sandero", "Clio"] },
  { brand: "Peugeot", models: ["208", "301", "308", "508", "2008", "3008", "5008", "Partner"] },
  { brand: "Skoda", models: ["Fabia", "Octavia", "Superb", "Kodiaq", "Karoq", "Kamiq"] },
  { brand: "Seat", models: ["Ibiza", "Leon", "Toledo", "Arona", "Ateca", "Tarraco"] },
  { brand: "Fiat", models: ["500", "Panda", "Tipo", "Egea", "Doblo", "Fiorino"] },
  { brand: "Jeep", models: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator"] },
  { brand: "Dodge", models: ["Charger", "Challenger", "Durango", "Journey"] },
  { brand: "GMC", models: ["Terrain", "Acadia", "Yukon", "Sierra", "Canyon"] },
  { brand: "Cadillac", models: ["CT4", "CT5", "XT4", "XT5", "XT6", "Escalade"] },
  { brand: "Subaru", models: ["Impreza", "Legacy", "XV", "Forester", "Outback", "WRX", "BRZ"] },
  { brand: "Volvo", models: ["S60", "S90", "XC40", "XC60", "XC90", "V60"] },
  { brand: "Porsche", models: ["718 Cayman", "718 Boxster", "Macan", "Cayenne", "Panamera", "Taycan"] },
  {
    brand: "Land Rover",
    models: ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Evoque", "Velar"],
  },
  { brand: "Jaguar", models: ["XE", "XF", "F-Pace", "E-Pace", "I-Pace"] },
  { brand: "Tesla", models: ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"] },
  { brand: "MG", models: ["MG3", "MG5", "MG6", "ZS", "HS", "RX5"] },
  { brand: "Changan", models: ["Alsvin", "Eado", "CS35", "CS55", "CS75", "UNI-T", "UNI-K"] },
  { brand: "Geely", models: ["Emgrand", "Coolray", "Azkarra", "Tugella", "Monjaro", "Geometry C"] },
  { brand: "Haval", models: ["Jolion", "H6", "H9", "Dargo"] },
  { brand: "Chery", models: ["Arrizo 5", "Arrizo 6", "Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8"] },
  { brand: "BYD", models: ["F3", "Qin", "Han", "Song", "Yuan", "Tang", "Dolphin", "Atto 3", "Seal"] },
  { brand: "Dongfeng", models: ["Shine", "S30", "AX7", "T5"] },
  { brand: "Isuzu", models: ["D-Max", "MU-X", "N-Series"] },
  { brand: "Great Wall", models: ["Wingle", "Poer", "Cannon"] },
  { brand: "Infiniti", models: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"] },
  { brand: "Acura", models: ["ILX", "TLX", "RDX", "MDX", "NSX"] },
  { brand: "Alfa Romeo", models: ["Giulia", "Stelvio", "Tonale"] },
];

export const modelProfiles = [
  {
    brand: "Toyota",
    model: "Corolla",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [28, 40],
    usedPriceM: [10, 30],
    fuelEfficiency: 9,
    comfort: 7,
    space: 6,
    resale: 10,
    maintenance: 9,
    reliability: 10,
    taxiFit: 9,
    personalFit: 8,
    workFit: 8,
  },
  {
    brand: "Toyota",
    model: "Camry",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [45, 62],
    usedPriceM: [20, 45],
    fuelEfficiency: 8,
    comfort: 9,
    space: 8,
    resale: 9,
    maintenance: 8,
    reliability: 9,
    taxiFit: 8,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Toyota",
    model: "Yaris",
    bodyType: "hatchback",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [22, 30],
    usedPriceM: [8, 20],
    fuelEfficiency: 9,
    comfort: 6,
    space: 5,
    resale: 8,
    maintenance: 9,
    reliability: 9,
    taxiFit: 8,
    personalFit: 7,
    workFit: 7,
  },
  {
    brand: "Toyota",
    model: "RAV4",
    bodyType: "suv",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [52, 75],
    usedPriceM: [28, 58],
    fuelEfficiency: 7,
    comfort: 8,
    space: 8,
    resale: 9,
    maintenance: 8,
    reliability: 9,
    taxiFit: 6,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Nissan",
    model: "Sunny",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [20, 28],
    usedPriceM: [7, 18],
    fuelEfficiency: 8,
    comfort: 6,
    space: 6,
    resale: 7,
    maintenance: 8,
    reliability: 8,
    taxiFit: 8,
    personalFit: 7,
    workFit: 7,
  },
  {
    brand: "Nissan",
    model: "Altima",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [39, 56],
    usedPriceM: [16, 38],
    fuelEfficiency: 7,
    comfort: 8,
    space: 8,
    resale: 7,
    maintenance: 7,
    reliability: 7,
    taxiFit: 6,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Hyundai",
    model: "Accent",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [18, 26],
    usedPriceM: [6, 17],
    fuelEfficiency: 8,
    comfort: 6,
    space: 6,
    resale: 7,
    maintenance: 8,
    reliability: 7,
    taxiFit: 8,
    personalFit: 7,
    workFit: 7,
  },
  {
    brand: "Hyundai",
    model: "Elantra",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [25, 36],
    usedPriceM: [9, 26],
    fuelEfficiency: 8,
    comfort: 7,
    space: 7,
    resale: 7,
    maintenance: 8,
    reliability: 7,
    taxiFit: 8,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Kia",
    model: "Rio",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [18, 26],
    usedPriceM: [6, 17],
    fuelEfficiency: 8,
    comfort: 6,
    space: 6,
    resale: 7,
    maintenance: 8,
    reliability: 7,
    taxiFit: 8,
    personalFit: 7,
    workFit: 7,
  },
  {
    brand: "Kia",
    model: "Cerato",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [24, 35],
    usedPriceM: [8, 24],
    fuelEfficiency: 7,
    comfort: 7,
    space: 7,
    resale: 7,
    maintenance: 8,
    reliability: 7,
    taxiFit: 7,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Honda",
    model: "Civic",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [35, 50],
    usedPriceM: [14, 35],
    fuelEfficiency: 8,
    comfort: 8,
    space: 7,
    resale: 8,
    maintenance: 7,
    reliability: 8,
    taxiFit: 7,
    personalFit: 9,
    workFit: 7,
  },
  {
    brand: "Mazda",
    model: "Mazda 3",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [30, 44],
    usedPriceM: [10, 30],
    fuelEfficiency: 7,
    comfort: 8,
    space: 6,
    resale: 7,
    maintenance: 7,
    reliability: 8,
    taxiFit: 6,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Suzuki",
    model: "Swift",
    bodyType: "hatchback",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [16, 24],
    usedPriceM: [5, 16],
    fuelEfficiency: 9,
    comfort: 5,
    space: 5,
    resale: 7,
    maintenance: 8,
    reliability: 8,
    taxiFit: 7,
    personalFit: 7,
    workFit: 6,
  },
  {
    brand: "BMW",
    model: "3 Series",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [75, 115],
    usedPriceM: [25, 70],
    fuelEfficiency: 6,
    comfort: 9,
    space: 7,
    resale: 7,
    maintenance: 4,
    reliability: 6,
    taxiFit: 3,
    personalFit: 9,
    workFit: 6,
  },
  {
    brand: "Mercedes-Benz",
    model: "C-Class",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [80, 125],
    usedPriceM: [28, 75],
    fuelEfficiency: 6,
    comfort: 9,
    space: 7,
    resale: 7,
    maintenance: 4,
    reliability: 6,
    taxiFit: 3,
    personalFit: 9,
    workFit: 6,
  },
  {
    brand: "Audi",
    model: "A4",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [78, 120],
    usedPriceM: [24, 70],
    fuelEfficiency: 6,
    comfort: 9,
    space: 7,
    resale: 6,
    maintenance: 4,
    reliability: 6,
    taxiFit: 2,
    personalFit: 9,
    workFit: 6,
  },
  {
    brand: "Tesla",
    model: "Model 3",
    bodyType: "sedan",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: true,
    newPriceM: [70, 110],
    usedPriceM: [45, 85],
    fuelEfficiency: 10,
    comfort: 8,
    space: 7,
    resale: 7,
    maintenance: 6,
    reliability: 7,
    taxiFit: 5,
    personalFit: 9,
    workFit: 7,
  },
  {
    brand: "Toyota",
    model: "Prado",
    bodyType: "suv",
    seats: 7,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [95, 150],
    usedPriceM: [45, 95],
    fuelEfficiency: 5,
    comfort: 8,
    space: 9,
    resale: 9,
    maintenance: 7,
    reliability: 9,
    taxiFit: 3,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Nissan",
    model: "Patrol",
    bodyType: "suv",
    seats: 7,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [120, 180],
    usedPriceM: [55, 120],
    fuelEfficiency: 4,
    comfort: 9,
    space: 9,
    resale: 9,
    maintenance: 6,
    reliability: 8,
    taxiFit: 2,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Hyundai",
    model: "Tucson",
    bodyType: "crossover",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [40, 60],
    usedPriceM: [18, 42],
    fuelEfficiency: 7,
    comfort: 8,
    space: 8,
    resale: 7,
    maintenance: 8,
    reliability: 7,
    taxiFit: 5,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Kia",
    model: "Sportage",
    bodyType: "crossover",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [42, 63],
    usedPriceM: [20, 45],
    fuelEfficiency: 7,
    comfort: 8,
    space: 8,
    resale: 7,
    maintenance: 8,
    reliability: 7,
    taxiFit: 5,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Chevrolet",
    model: "Tahoe",
    bodyType: "suv",
    seats: 7,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [110, 170],
    usedPriceM: [45, 110],
    fuelEfficiency: 4,
    comfort: 9,
    space: 10,
    resale: 8,
    maintenance: 5,
    reliability: 6,
    taxiFit: 2,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Ford",
    model: "Explorer",
    bodyType: "suv",
    seats: 7,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [95, 145],
    usedPriceM: [35, 95],
    fuelEfficiency: 5,
    comfort: 8,
    space: 9,
    resale: 7,
    maintenance: 5,
    reliability: 6,
    taxiFit: 2,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Jeep",
    model: "Grand Cherokee",
    bodyType: "suv",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [105, 165],
    usedPriceM: [36, 105],
    fuelEfficiency: 5,
    comfort: 8,
    space: 8,
    resale: 7,
    maintenance: 5,
    reliability: 6,
    taxiFit: 2,
    personalFit: 9,
    workFit: 7,
  },
  {
    brand: "GMC",
    model: "Yukon",
    bodyType: "suv",
    seats: 7,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [125, 190],
    usedPriceM: [50, 125],
    fuelEfficiency: 4,
    comfort: 9,
    space: 10,
    resale: 8,
    maintenance: 5,
    reliability: 6,
    taxiFit: 2,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Cadillac",
    model: "Escalade",
    bodyType: "suv",
    seats: 7,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [150, 220],
    usedPriceM: [70, 150],
    fuelEfficiency: 4,
    comfort: 10,
    space: 10,
    resale: 8,
    maintenance: 4,
    reliability: 6,
    taxiFit: 1,
    personalFit: 9,
    workFit: 7,
  },
  {
    brand: "Subaru",
    model: "Forester",
    bodyType: "crossover",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [45, 65],
    usedPriceM: [20, 45],
    fuelEfficiency: 7,
    comfort: 7,
    space: 8,
    resale: 7,
    maintenance: 7,
    reliability: 8,
    taxiFit: 4,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Volvo",
    model: "XC60",
    bodyType: "suv",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [95, 145],
    usedPriceM: [35, 95],
    fuelEfficiency: 6,
    comfort: 9,
    space: 8,
    resale: 7,
    maintenance: 5,
    reliability: 7,
    taxiFit: 2,
    personalFit: 9,
    workFit: 7,
  },
  {
    brand: "Porsche",
    model: "Cayenne",
    bodyType: "suv",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [160, 260],
    usedPriceM: [70, 160],
    fuelEfficiency: 5,
    comfort: 9,
    space: 8,
    resale: 7,
    maintenance: 4,
    reliability: 6,
    taxiFit: 1,
    personalFit: 9,
    workFit: 6,
  },
  {
    brand: "Land Rover",
    model: "Defender",
    bodyType: "suv",
    seats: 7,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [145, 230],
    usedPriceM: [70, 160],
    fuelEfficiency: 4,
    comfort: 9,
    space: 9,
    resale: 7,
    maintenance: 4,
    reliability: 5,
    taxiFit: 1,
    personalFit: 9,
    workFit: 8,
  },
  {
    brand: "Jaguar",
    model: "F-Pace",
    bodyType: "suv",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: true,
    isElectric: false,
    newPriceM: [110, 170],
    usedPriceM: [45, 110],
    fuelEfficiency: 5,
    comfort: 9,
    space: 8,
    resale: 6,
    maintenance: 4,
    reliability: 5,
    taxiFit: 1,
    personalFit: 9,
    workFit: 7,
  },
  {
    brand: "MG",
    model: "ZS",
    bodyType: "crossover",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [28, 42],
    usedPriceM: [14, 30],
    fuelEfficiency: 7,
    comfort: 7,
    space: 7,
    resale: 6,
    maintenance: 7,
    reliability: 6,
    taxiFit: 6,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Changan",
    model: "CS35",
    bodyType: "crossover",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [26, 38],
    usedPriceM: [12, 28],
    fuelEfficiency: 7,
    comfort: 6,
    space: 7,
    resale: 6,
    maintenance: 7,
    reliability: 6,
    taxiFit: 6,
    personalFit: 7,
    workFit: 7,
  },
  {
    brand: "Geely",
    model: "Coolray",
    bodyType: "crossover",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [30, 45],
    usedPriceM: [16, 34],
    fuelEfficiency: 7,
    comfort: 7,
    space: 7,
    resale: 6,
    maintenance: 7,
    reliability: 6,
    taxiFit: 5,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Haval",
    model: "H6",
    bodyType: "suv",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [40, 58],
    usedPriceM: [22, 45],
    fuelEfficiency: 6,
    comfort: 7,
    space: 8,
    resale: 6,
    maintenance: 6,
    reliability: 6,
    taxiFit: 4,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Chery",
    model: "Tiggo 7",
    bodyType: "suv",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [35, 52],
    usedPriceM: [18, 38],
    fuelEfficiency: 6,
    comfort: 7,
    space: 8,
    resale: 6,
    maintenance: 7,
    reliability: 6,
    taxiFit: 5,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "BYD",
    model: "Atto 3",
    bodyType: "crossover",
    seats: 5,
    hasAutomatic: true,
    hasManual: false,
    hasHybrid: false,
    isElectric: true,
    newPriceM: [55, 85],
    usedPriceM: [35, 65],
    fuelEfficiency: 10,
    comfort: 8,
    space: 8,
    resale: 7,
    maintenance: 7,
    reliability: 7,
    taxiFit: 6,
    personalFit: 8,
    workFit: 7,
  },
  {
    brand: "Isuzu",
    model: "D-Max",
    bodyType: "pickup",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [50, 78],
    usedPriceM: [20, 55],
    fuelEfficiency: 6,
    comfort: 6,
    space: 8,
    resale: 8,
    maintenance: 8,
    reliability: 8,
    taxiFit: 3,
    personalFit: 7,
    workFit: 10,
  },
  {
    brand: "Great Wall",
    model: "Poer",
    bodyType: "pickup",
    seats: 5,
    hasAutomatic: true,
    hasManual: true,
    hasHybrid: false,
    isElectric: false,
    newPriceM: [45, 72],
    usedPriceM: [24, 55],
    fuelEfficiency: 6,
    comfort: 6,
    space: 8,
    resale: 6,
    maintenance: 7,
    reliability: 7,
    taxiFit: 3,
    personalFit: 7,
    workFit: 9,
  },
];

export const brandTierRanges = {
  economy: {
    newPriceM: [18, 40],
    usedPriceM: [6, 24],
  },
  mid: {
    newPriceM: [35, 75],
    usedPriceM: [14, 50],
  },
  premium: {
    newPriceM: [75, 145],
    usedPriceM: [28, 95],
  },
  luxury: {
    newPriceM: [120, 250],
    usedPriceM: [55, 165],
  },
};

export const brandTierMap = {
  Toyota: "mid",
  Nissan: "mid",
  Hyundai: "economy",
  Kia: "economy",
  Chevrolet: "mid",
  Ford: "mid",
  Honda: "mid",
  Mazda: "mid",
  Mitsubishi: "economy",
  Suzuki: "economy",
  Volkswagen: "mid",
  BMW: "premium",
  "Mercedes-Benz": "premium",
  Audi: "premium",
  Lexus: "premium",
  Renault: "economy",
  Peugeot: "economy",
  Skoda: "economy",
  Seat: "economy",
  Fiat: "economy",
  Jeep: "premium",
  Dodge: "premium",
  GMC: "luxury",
  Cadillac: "luxury",
  Subaru: "mid",
  Volvo: "premium",
  Porsche: "luxury",
  "Land Rover": "luxury",
  Jaguar: "luxury",
  Tesla: "premium",
  MG: "economy",
  Changan: "economy",
  Geely: "economy",
  Haval: "economy",
  Chery: "economy",
  BYD: "mid",
  Dongfeng: "economy",
  Isuzu: "mid",
  "Great Wall": "mid",
  Infiniti: "premium",
  Acura: "premium",
  "Alfa Romeo": "premium",
};

export function normalizeKey(value) {
  return String(value || "").trim().toLowerCase();
}

export function getCatalogBrand(brand) {
  const key = normalizeKey(brand);
  return carCatalog.find((item) => normalizeKey(item.brand) === key) || null;
}

export function profileKey(brand, model) {
  return `${normalizeKey(brand)}|${normalizeKey(model)}`;
}
